/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'
import { Route as SearchResultsTransactionIdRouteImport } from './routes/search-results/$transactionId'
import { Route as SearchResultsStreamedTransactionIdRouteImport } from './routes/search-results-streamed/$transactionId'
import { Route as MotorSearchIdRouteImport } from './routes/motor/$searchId'
import { Route as HealthSearchIdRouteImport } from './routes/health/$searchId'
import { Route as QuoteTransactionIdMessageIdRouteImport } from './routes/quote/$transactionId/$messageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsTransactionIdRoute =
  SearchResultsTransactionIdRouteImport.update({
    id: '/search-results/$transactionId',
    path: '/search-results/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SearchResultsStreamedTransactionIdRoute =
  SearchResultsStreamedTransactionIdRouteImport.update({
    id: '/search-results-streamed/$transactionId',
    path: '/search-results-streamed/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MotorSearchIdRoute = MotorSearchIdRouteImport.update({
  id: '/motor/$searchId',
  path: '/motor/$searchId',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSearchIdRoute = HealthSearchIdRouteImport.update({
  id: '/health/$searchId',
  path: '/health/$searchId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTransactionIdMessageIdRoute =
  QuoteTransactionIdMessageIdRouteImport.update({
    id: '/quote/$transactionId/$messageId',
    path: '/quote/$transactionId/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health/$searchId': typeof HealthSearchIdRoute
  '/motor/$searchId': typeof MotorSearchIdRoute
  '/search-results-streamed/$transactionId': typeof SearchResultsStreamedTransactionIdRoute
  '/search-results/$transactionId': typeof SearchResultsTransactionIdRoute
  '/directory/': typeof DirectoryIndexRoute
  '/quote/$transactionId/$messageId': typeof QuoteTransactionIdMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health/$searchId': typeof HealthSearchIdRoute
  '/motor/$searchId': typeof MotorSearchIdRoute
  '/search-results-streamed/$transactionId': typeof SearchResultsStreamedTransactionIdRoute
  '/search-results/$transactionId': typeof SearchResultsTransactionIdRoute
  '/directory': typeof DirectoryIndexRoute
  '/quote/$transactionId/$messageId': typeof QuoteTransactionIdMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health/$searchId': typeof HealthSearchIdRoute
  '/motor/$searchId': typeof MotorSearchIdRoute
  '/search-results-streamed/$transactionId': typeof SearchResultsStreamedTransactionIdRoute
  '/search-results/$transactionId': typeof SearchResultsTransactionIdRoute
  '/directory/': typeof DirectoryIndexRoute
  '/quote/$transactionId/$messageId': typeof QuoteTransactionIdMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health/$searchId'
    | '/motor/$searchId'
    | '/search-results-streamed/$transactionId'
    | '/search-results/$transactionId'
    | '/directory/'
    | '/quote/$transactionId/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health/$searchId'
    | '/motor/$searchId'
    | '/search-results-streamed/$transactionId'
    | '/search-results/$transactionId'
    | '/directory'
    | '/quote/$transactionId/$messageId'
  id:
    | '__root__'
    | '/'
    | '/health/$searchId'
    | '/motor/$searchId'
    | '/search-results-streamed/$transactionId'
    | '/search-results/$transactionId'
    | '/directory/'
    | '/quote/$transactionId/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthSearchIdRoute: typeof HealthSearchIdRoute
  MotorSearchIdRoute: typeof MotorSearchIdRoute
  SearchResultsStreamedTransactionIdRoute: typeof SearchResultsStreamedTransactionIdRoute
  SearchResultsTransactionIdRoute: typeof SearchResultsTransactionIdRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  QuoteTransactionIdMessageIdRoute: typeof QuoteTransactionIdMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results/$transactionId': {
      id: '/search-results/$transactionId'
      path: '/search-results/$transactionId'
      fullPath: '/search-results/$transactionId'
      preLoaderRoute: typeof SearchResultsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results-streamed/$transactionId': {
      id: '/search-results-streamed/$transactionId'
      path: '/search-results-streamed/$transactionId'
      fullPath: '/search-results-streamed/$transactionId'
      preLoaderRoute: typeof SearchResultsStreamedTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motor/$searchId': {
      id: '/motor/$searchId'
      path: '/motor/$searchId'
      fullPath: '/motor/$searchId'
      preLoaderRoute: typeof MotorSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$searchId': {
      id: '/health/$searchId'
      path: '/health/$searchId'
      fullPath: '/health/$searchId'
      preLoaderRoute: typeof HealthSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$transactionId/$messageId': {
      id: '/quote/$transactionId/$messageId'
      path: '/quote/$transactionId/$messageId'
      fullPath: '/quote/$transactionId/$messageId'
      preLoaderRoute: typeof QuoteTransactionIdMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthSearchIdRoute: HealthSearchIdRoute,
  MotorSearchIdRoute: MotorSearchIdRoute,
  SearchResultsStreamedTransactionIdRoute:
    SearchResultsStreamedTransactionIdRoute,
  SearchResultsTransactionIdRoute: SearchResultsTransactionIdRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  QuoteTransactionIdMessageIdRoute: QuoteTransactionIdMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
